openapi: 3.0.3
info:
  title:  Rest API
  description: All Item Rest API End Points
  version: V-2024-04
servers:
  - url: http://localhost:8080
tags:
  - name: User
paths:
  /user/register:
    post:
      tags:
        - User
      summary: registration of a new user
      description: registration of a new user
      operationId: registerUser
      requestBody:
        description: User data to create
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterUserDTO'
      responses:
        201:
          description: successful operation
          content:
            application/json:
              schema:
                type: string
                format: uuid

components:
  schemas:
    RegisterUserDTO:
      required:
        - emailAddress
        - password
        - countryCode
        - number
        - firstName
        - lastName
        - genre
      type: object
      properties:
        emailAddress:
          type: string
          description: user email
        password:
          type: string
          description: user password
        countryCode:
          type: string
          description: country code
          example: 237 for Cameroon country
        number:
          type: string
          description: phone number
          example: 677891234
        firstName:
          type: string
          description: User first name
        lastName:
          type: string
          description: User last name
        dateOfBirth:
          type: string
          format: date
        genre:
          $ref: '#/components/schemas/GenreDTO'
    GenreDTO:
      type: string
      enum:
        - MALE
        - FEMALE